Bump playwright from 1.11.1 to 1.12.3 (#502)
Bumps [playwright](https://github.com/Microsoft/playwright) from 1.11.1 to 1.12.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/Microsoft/playwright/releases">playwright's releases</a>.</em></p>
<blockquote>
<h2>v1.12.3</h2>
<h2>Highlights</h2>
<p>This patch release includes bug fixes for the following issues:</p>
<p><a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7085">#7085</a> - [BUG] Traceviewer screens are not recorded well when using constructable stylesheets
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7093">#7093</a> - Folder for a test-case is getting generated in test-results even if Test Case Passes when properties are given on Failure
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7099">#7099</a> - [test-runner] Missing types for the expect library
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7124">#7124</a> - [Test Runner] config.outputDir must be an absolute path
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7141">#7141</a> - [Feature] Options for video resolution
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7163">#7163</a> - [Test runner] artifacts are removed
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7223">#7223</a> - [BUG] test-runner viewport can't be null
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7284">#7284</a> - [BUG] incorrect <code>@​playwright/test</code> typings for toMatchSnapshot/toMatchInlineSnapshot/etc
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7304">#7304</a> - [BUG] Snapshots are not captured if there is an animation at the beginning
<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7326">#7326</a> - [BUG] When PW timeouts, last trace action does not get collected[BUG] When PW timeouts, last trace action does not get collected</p>
<h2>Browser Versions</h2>
<ul>
<li>Chromium 93.0.4530.0</li>
<li>Mozilla Firefox 89.0</li>
<li>WebKit 14.2</li>
</ul>
<p>This version of Playwright was also tested against the following stable channels:</p>
<ul>
<li>Google Chrome 91</li>
<li>Microsoft Edge 91</li>
</ul>
<h2>v1.12.2</h2>
<h2>Highlights</h2>
<p>This patch release includes bugfixes for the following issues:</p>
<ul>
<li><a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7015">#7015</a> - [BUG] Firefox: strange undefined toJSON property on JS objects</li>
<li><a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7004">#7004</a> - [test runner] Error: Error while reading global-setup.ts: Cannot find module 'global-setup.ts'</li>
<li><a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7048">#7048</a> - [BUG] Dialogs cannot be dismissed if tracing is on in Chromium or Webkit</li>
<li><a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7058">#7058</a> - [BUG] Getting no video frame error for mobile chrome</li>
<li><a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7020">#7020</a> - [Feature] Codegen should be able to emit <code>@​playwright/test</code> syntax</li>
</ul>
<h2>Browser Versions</h2>
<ul>
<li>Chromium 93.0.4530.0</li>
<li>Mozilla Firefox 89.0</li>
<li>WebKit 14.2</li>
</ul>
<p>This version of Playwright was also tested against the following stable channels:</p>
<ul>
<li>Google Chrome 91</li>
<li>Microsoft Edge 91</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/microsoft/playwright/commit/027b294bd7538bba8632cf3dfc20600601ad3bb5"><code>027b294</code></a> cherry-pick(release-1.12): fix default export breaking on installation tests ...</li>
<li><a href="https://github.com/microsoft/playwright/commit/81d4b4334b43f5884d562db3e36fb6835783aafe"><code>81d4b43</code></a> cherry-pick(release-1.12): account for last child node removal (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7335">#7335</a>)</li>
<li><a href="https://github.com/microsoft/playwright/commit/c25e00be619fc57ab3dee698add23c423fecaa3f"><code>c25e00b</code></a> cherry-pick(release-1.12): support constructed CSSStyleSheet (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7334">#7334</a>)</li>
<li><a href="https://github.com/microsoft/playwright/commit/6a2175ef652cd22d4cbd9af17d69d2a9dd6dbaeb"><code>6a2175e</code></a> cherry-pick(release-1.12): show interrupted actions in trace (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7333">#7333</a>)</li>
<li><a href="https://github.com/microsoft/playwright/commit/f52332af3c4c139a3f832c894513fd30705f89ef"><code>f52332a</code></a> chore: mark v1.12.3 (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7323">#7323</a>)</li>
<li><a href="https://github.com/microsoft/playwright/commit/6879b9b9c6408934ee82c22d0ae19d106ee2a9b3"><code>6879b9b</code></a> cherry-pick(release-1.12): have the proper default export (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7328">#7328</a>) (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7330">#7330</a>)</li>
<li><a href="https://github.com/microsoft/playwright/commit/2de5deb92641d340498f9ca4197783fbdfbfd174"><code>2de5deb</code></a> cherry-pick(release-1.12): move OverriddenExpectProperties outside the namesp...</li>
<li><a href="https://github.com/microsoft/playwright/commit/96fc610408e0661b0f2a9fded81be52a59513e02"><code>96fc610</code></a> cherry-pick(release-1.12): default <code>@​playwright/test</code> timeout to 0 (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7321">#7321</a>)</li>
<li><a href="https://github.com/microsoft/playwright/commit/770fce53e76bb4bdb96b06bbb80453c5f10022ff"><code>770fce5</code></a> cherry-pick(release-1.12): remove unimplemented jest expect types (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7311">#7311</a>)</li>
<li><a href="https://github.com/microsoft/playwright/commit/dd153b3dd763fe7778e8057b67b97b680df34e33"><code>dd153b3</code></a> cherry-pick(release-1.12): allow viewport null values (<a href="https://github-redirect.dependabot.com/Microsoft/playwright/issues/7310">#7310</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/Microsoft/playwright/compare/v1.11.1...v1.12.3">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=playwright&package-manager=npm_and_yarn&previous-version=1.11.1&new-version=1.12.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

You can trigger a rebase of this PR by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>